### ISSUE TITLE
Python 3.12 support

### ISSUE THREAD

**Issue by jstucke** [fkie-cad/entropython#1]
Please add a pre-built wheel for Python 3.12

**Comment by ElDavoo** [comment]
@Enkelmann

**Comment by ElDavoo** [comment]
@jstucke Not solved: the pre-built wheel is still not published on PyPI.

**Comment by jstucke** [comment]
> @jstucke Not solved: the pre-built wheel is still not published on PyPI.

I'm aware of this and there will be a new binary release when @Enkelmann provides me with access to the project on PyPI (which should be soon)

But you can technically already install the package on Python 3.12 if you have a Rust compiler installed and install directly from the repository.

**Comment by ElDavoo** [comment]
> > @jstucke Not solved: the pre-built wheel is still not published on PyPI.
> 
> I'm aware of this and there will be a new binary release when @Enkelmann provides me with access to the project on PyPI (which should be soon)

Great!

> But you can technically already install the package on Python 3.12 if you have a Rust compiler installed and install directly from the repository.

Too lazy to do it xD Will just wait

**Comment by jstucke** [comment]
> Too lazy to do it xD Will just wait

If everything worked, the new release should now be available: https://pypi.org/project/entropython/1.1.0/#files
