### ISSUE TITLE
pypi aarch64 build

### ISSUE THREAD

**Issue by soxrok2212** [fkie-cad/entropython#2]
Hi, kindly requesting that an aarch64 build be pushed to pypi in support of running FACT on arm.

**Comment by jstucke** [comment]
Could you try if #3 also works with arm64? In theory, it should simply install when you run (needs a Rust compiler)
```sh
pip install git+https://github.com/fkie-cad/entropython@7753a3e
```

**Comment by soxrok2212** [comment]
Installs just fine! 👍

**Comment by jstucke** [comment]
I just pushed a new release to PyPI and it should also contain pre-built aarch64 wheels and also a source package

**Comment by soxrok2212** [comment]
Works, thank you!
